# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: bryanpedlarcom # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
plugins:
  - site-uploader

provider:
  name: aws
  runtime: python2.7

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

custom:
  domainName: bryanpedlar.com
  site_bucket: ${self:custom.domainName}
  site_dir: site

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - site/**
    - node_modules/**
#    - exclude-me-dir/**

#functions:
#  hello:
#    handler: handler.hello

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
resources:
  Resources:
    DNS: 
      Type: "AWS::Route53::HostedZone"
      Properties: 
        HostedZoneConfig: 
          Comment: "My hosted zone for ${self:custom.domainName}"
        Name: ${self:custom.domainName}
    bryanpedlarcombucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.domainName}
        WebsiteConfiguration: 
          IndexDocument: "index.html"
          ErrorDocument: "error.html"
    wwwbryanpedlarcombucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: www.${self:custom.domainName}
        WebsiteConfiguration:
          RedirectAllRequestsTo:
            HostName: ${self:custom.domainName}
            Protocol: http
    bryanpedlarcombucketPolicy: 
      DependsOn: bryanpedlarcombucket
      Type: "AWS::S3::BucketPolicy"
      Properties: 
        Bucket: 
          Ref: "bryanpedlarcombucket"
        PolicyDocument: 
          Statement: 
            - 
              Action: 
                - "s3:GetObject"
              Effect: "Allow"
              Resource: 
                Fn::Join: 
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - 
                      Ref: "bryanpedlarcombucket"
                    - "/*"
              Principal: "*"
    wwwbryanpedlarcombucketPolicy: 
      DependsOn: wwwbryanpedlarcombucket
      Type: "AWS::S3::BucketPolicy"
      Properties: 
        Bucket: 
          Ref: "wwwbryanpedlarcombucket"
        PolicyDocument: 
          Statement: 
            - 
              Action: 
                - "s3:GetObject"
              Effect: "Allow"
              Resource: 
                Fn::Join: 
                  - ""
                  - 
                    - "arn:aws:s3:::"
                    - 
                      Ref: "wwwbryanpedlarcombucket"
                    - "/*"
              Principal: "*"
    myDNS:
      DependsOn: DNS
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: ${self:custom.domainName}.
        Comment: Zone apex alias.
        RecordSets:
        - 
          Name: ${self:custom.domainName}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: 
              "Fn::GetAtt": [ myCDN, DomainName ]
        -
          Name: www.${self:custom.domainName}
          Type: CNAME
          TTL: 60
          ResourceRecords:
          - ${self:custom.domainName}
    mycert:
      DependsOn: bryanpedlarcombucket
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: ${self:custom.domainName}
        SubjectAlternativeNames:
          - www.${self:custom.domainName}
    myCDN:
      DependsOn: mycert
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          Origins:
          - DomainName: ${self:custom.domainName}.s3.amazonaws.com
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
          Enabled: 'true'
          Comment: Some comment
          DefaultRootObject: index.html
          Aliases:
          - ${self:custom.domainName}
          - www.${self:custom.domainName}
          DefaultCacheBehavior:
            AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
            # redirect-to-https
          PriceClass: PriceClass_200
          ViewerCertificate:
            AcmCertificateArn: 
              Ref: mycert
            SslSupportMethod: sni-only
